# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ANTAlg(object):
    def setupUi(self, ANTAlg):
        ANTAlg.setObjectName("ANTAlg")
        ANTAlg.resize(622, 485)
        self.pushButton = QtWidgets.QPushButton(ANTAlg)
        self.pushButton.setGeometry(QtCore.QRect(250, 430, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(ANTAlg)
        self.lineEdit.setGeometry(QtCore.QRect(360, 30, 201, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(ANTAlg)
        self.lineEdit_2.setGeometry(QtCore.QRect(360, 90, 201, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(ANTAlg)
        self.lineEdit_3.setGeometry(QtCore.QRect(360, 150, 201, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(ANTAlg)
        self.lineEdit_4.setGeometry(QtCore.QRect(360, 210, 201, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label = QtWidgets.QLabel(ANTAlg)
        self.label.setGeometry(QtCore.QRect(60, 30, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(ANTAlg)
        self.label_2.setGeometry(QtCore.QRect(60, 100, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(ANTAlg)
        self.label_3.setGeometry(QtCore.QRect(60, 160, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(ANTAlg)
        self.label_4.setGeometry(QtCore.QRect(60, 220, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(ANTAlg)
        self.lineEdit_5.setGeometry(QtCore.QRect(360, 270, 201, 31))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_5 = QtWidgets.QLabel(ANTAlg)
        self.label_5.setGeometry(QtCore.QRect(64, 280, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(ANTAlg)
        self.lineEdit_6.setGeometry(QtCore.QRect(360, 330, 201, 31))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_6 = QtWidgets.QLabel(ANTAlg)
        self.label_6.setGeometry(QtCore.QRect(60, 330, 301, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(ANTAlg)
        self.lineEdit_7.setGeometry(QtCore.QRect(360, 390, 201, 31))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_7 = QtWidgets.QLabel(ANTAlg)
        self.label_7.setGeometry(QtCore.QRect(60, 390, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")

        self.retranslateUi(ANTAlg)
        QtCore.QMetaObject.connectSlotsByName(ANTAlg)

    def retranslateUi(self, ANTAlg):
        _translate = QtCore.QCoreApplication.translate
        ANTAlg.setWindowTitle(_translate("ANTAlg", "ANT"))
        self.pushButton.setText(_translate("ANTAlg", "Ok"))
        self.label.setText(_translate("ANTAlg", "Число муравьев"))
        self.label_2.setText(_translate("ANTAlg", "Количество итераций"))
        self.label_3.setText(_translate("ANTAlg", "Альфа"))
        self.label_4.setText(_translate("ANTAlg", "Бетта"))
        self.label_5.setText(_translate("ANTAlg", "Число вершин"))
        self.label_6.setText(_translate("ANTAlg", "Коэффициент испарения ферромона"))
        self.label_7.setText(_translate("ANTAlg", "Интенсивность ферромонов"))
